[colors.primary]
background = "#23262d"
foreground = "#bbc2cf"

[colors.cursor]
text       = "#282c34"
cursor     = "#bbc2cf"

[colors.selection]
text       = "#282c34"
background = "#3e4452"

[colors.normal]
black   = "#1c1f24"
red     = "#ff6c6b"
green   = "#98be65"
yellow  = "#da8548"
blue    = "#51afef"
magenta = "#c678dd"
cyan    = "#5699af"
white   = "#202328"

[colors.bright]
black   = "#5b6268"
red     = "#da8548"
green   = "#4db5bd"
yellow  = "#ecbe7b"
blue    = "#2257a0"
magenta = "#a9a1e1"
cyan    = "#46d9ff"
white   = "#dfdfdf"
