[colors.primary]
background = "#F2EAD2"
foreground = "#5c6a72"

[colors.cursor]
text       = "#f3ead3"
cursor     = "#5c6a72"

[colors.selection]
text       = "#5c6a72"
background = "#e6dfc9"

[colors.normal]
black   = "#5c6a72"
red     = "#f85552"
green   = "#8da101"
yellow  = "#dfa000"
blue    = "#3a94c5"
magenta = "#df69ba"
cyan    = "#35a77c"
white   = "#dfddc8"

[colors.bright]
black   = "#939f91"
red     = "#f85552"
green   = "#8da101"
yellow  = "#dfa000"
blue    = "#3a94c5"
magenta = "#df69ba"
cyan    = "#35a77c"
white   = "#f3ead3"

