[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.cursor]
text       = "#000000"
cursor     = "#ffffff"

[colors.selection]
text       = "#000000"
background = "#2c2c2c"

[colors.normal]
black   = "#000000"
red     = "#ff5c57"
green   = "#5af78e"
yellow  = "#f3f99d"
blue    = "#57c7ff"
magenta = "#ff6ac1"
cyan    = "#9aedfe"
white   = "#eaeaea"

[colors.bright]
black   = "#444444"
red     = "#ff8b8b"
green   = "#7fffaa"
yellow  = "#fdf6c8"
blue    = "#9bddff"
magenta = "#ff9bde"
cyan    = "#bafeff"
white   = "#ffffff"
