[colors.primary]
background = "#F2EBBC"
foreground = "#545464"

[colors.cursor]
text       = "#F2EBBC"
cursor     = "#545464"

[colors.selection]
text       = "#545464"
background = "#dcd3c2"

[colors.normal]
black   = "#56526e"
red     = "#c84053"
green   = "#6f894e"
yellow  = "#77713f"
blue    = "#4d699b"
magenta = "#b35b79"
cyan    = "#597b75"
white   = "#e8e5da"

[colors.bright]
black   = "#8a8980"
red     = "#d7474b"
green   = "#6e915f"
yellow  = "#836f4a"
blue    = "#5a77a8"
magenta = "#c06f89"
cyan    = "#5e857a"
white   = "#f2ecde"

