[colors.primary]
background = "#1E232A"
foreground = "#abb2bf"

[colors.cursor]
text       = "#1E232A"
cursor     = "#528bff"

[colors.selection]
text       = "#abb2bf"
background = "#2c313c"

[colors.normal]
black   = "#1e2127"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#abb2bf"

[colors.bright]
black   = "#5c6370"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#ffffff"
