[colors.primary]
background = "#1e1e2e"
foreground = "#c6c6c6"

[colors.cursor]
text       = "#1e1e2e"
cursor     = "#f5c2e7"

[colors.selection]
text       = "#1e1e2e"
background = "#f5c2e7"

[colors.normal]
black   = "#1e1e2e"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#cdd6f4"

[colors.bright]
black   = "#585b70"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#ffffff"
