[colors.primary]
background = "#00141A"
foreground = "#657b83"

[colors.cursor]
text       = "#012B36"
cursor     = "#839496"

[colors.selection]
text       = "#012B36"
background = "#2aa198"

[colors.normal]
black   = "#657b83"
red     = "#DC322F"
green   = "#859901"
yellow  = "#B58900"
blue    = "#278BD2"
magenta = "#D43682"
cyan    = "#2AA198"
white   = "#fdf6e3"

[colors.bright]
black   = "#657b83"
red     = "#DC322F"
green   = "#859901"
yellow  = "#B58900"
blue    = "#278BD2"
magenta = "#D43682"
cyan    = "#2AA198"
white   = "#fdf6e3"

