[colors.primary]
background = "#21282c"
foreground = "#d3c6aa"

[colors.cursor]
text       = "#2d353b"
cursor     = "#d3c6aa"

[colors.selection]
text       = "#2d353b"
background = "#503946"

[colors.normal]
black   = "#475258"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"

[colors.bright]
black   = "#475258"
red     = "#e67e80"
green   = "#a7c080"
yellow  = "#dbbc7f"
blue    = "#7fbbb3"
magenta = "#d699b6"
cyan    = "#83c092"
white   = "#d3c6aa"
