[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = false
decorations = "full"
title = "Alacritty@CachyOS"
opacity = 1
decorations_theme_variant = "Dark"

[window.padding]
x = 8
y = 8

[window.dimensions]
columns = 100
lines = 20

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

# Colors (Solarized Osaka)
# Source https://github.com/craftzdog/solarized-osaka.nvim

# Default colors
[colors.primary]
background = '#001a1d'
foreground = '#839496'

# Normal colors
[colors.normal]
black   = '#073642'
red     = '#dc322f'
green   = '#859900'
yellow  = '#b58900'
blue    = '#268bd2'
magenta = '#d33682'
cyan    = '#2aa198'
white   = '#eee8d5'

# Bright colors
[colors.bright]
black   = '#4c4c4c'
red     = '#cb4b16'
green   = '#586e75'
yellow  = '#657b83'
blue    = '#839496'
magenta = '#6c71c4'
cyan    = '#93a1a1'
white   = '#fdf6e3'

[font]
size = 18

[font.normal]
family = "IosevkaTerm Nerd Font"
style = "Semibold"

[font.bold]
family = "IosevkaTerm Nerd Font"
style = "Bold"

[font.italic]
family = "IosevkaTerm Nerd Font"
style = "Italic"

[font.bold_italic]
family = "IosevkaTerm Nerd Font"
style = "Bold Italic"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Beam"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[general]
live_config_reload = true
working_directory = "None"
